apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    k8s-app: heapster
    name: heapster
    version: v6
  name: heapster-v6
  namespace: kube-system
spec:
  replicas: 1
  selector:
    k8s-app: heapster
    version: v6
  template:
    metadata:
      labels:
        k8s-app: heapster
        version: v6
    spec:
      containers:
      - name: heapster
        image: we87/heapster:v0.18.1-we87-2
        command:
        - /heapster
        - --source=kubernetes:http://as-internal.k8s.us:8080?inClusterConfig=false
        - --sink=influxdb:http://monitoring-influxdb:8086
