apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: influxGrafana
    version: v2
    k8s.us/cluster-service: "true"
  name: influxdb-grafana-v2
  namespace: kube-system
spec:
  replicas: 1
  selector:
    name: influxGrafana
    version: v2
  template:
    metadata:
      labels:
        name: influxGrafana
        version: v2
        k8s.us/cluster-service: "true"
    spec:
      containers:
      - name: influxdb
        image: kubernetes/heapster_influxdb:v0.5
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - mountPath: /data
          name: influxdb-storage
      - name: grafana
        image: kubernetes/heapster_grafana:v2.1.0
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        env:
          - name: INFLUXDB_SERVICE_URL
            value: http://monitoring-influxdb:8086
            # The following env variables are required to make Grafana accessible via
            # the kubernetes api-server proxy. On production clusters, we recommend
            # removing these env variables, setup auth for grafana, and expose the grafana
            # service using a LoadBalancer or a public IP.
          - name: GF_AUTH_BASIC_ENABLED
            value: "false"
          - name: GF_AUTH_ANONYMOUS_ENABLED
            value: "true"
          - name: GF_AUTH_ANONYMOUS_ORG_ROLE
            value: Admin
        volumeMounts:
        - mountPath: /var
          name: grafana-storage
      volumes:
      - name: influxdb-storage
        emptyDir: {}
      - name: grafana-storage
        emptyDir: {}
